name: Github actions

on:
  push:
    tags:
      - "deploy/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: "npm i"
      - run: "npm run test"
      - run: npm install -g clever-tools
      - run: "git pull origin main --unshallow"
      - run: clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
      - run: clever deploy -f
